### ISSUE TITLE
Inspired with your story on Quora

### ISSUE THREAD

**Issue by Bhaskersadak** [Ritiek/ama#11]
Hi Ritiek,I too faced problems with my academics bcoz I failed in 22 subjects of my B-Tech..Everyone thought I'm a failure but I never cared bcoz I was passionate in stock market.
Currently I working for a Dubai stock agency that too from home with a mind blowing salary ...

**Comment by Ritiek** [comment]
Awesome! Thanks for sharing your story and good luck with your agency :)
