### ISSUE TITLE
Read your answer on Quora

### ISSUE THREAD

**Issue by iamalsaher** [Ritiek/ama#13]
Hi Ritiek, I am impressed, but yeah I did clear Jee mains 72K Rank and stuff. How old are you and which sphere of IT you wanna get in. Also, are you in Snapchat? I am 18, we can be good friends

**Comment by Ritiek** [comment]
Hi, I'm 17. I think I want to get into machine learning and more into neural networks but I'm not exactly sure. I'll have to work on my Math though. No, I don't use snapchat.
