### ISSUE TITLE
I'm also like you

### ISSUE THREAD

**Issue by TheVip** [Ritiek/ama#3]
I am not selected in JEE 2017. My parents want me to repeat. I know if I drop I'll be selected. But I don't want to waste my time. I am interested in programming. I  know Html,Css,Javascript and i'm learning python and C++ . I want to get into machine learning, can you suggest me where should I start?

**Comment by Ritiek** [comment]
Check out #2. I do not know C++ so I cannot tell you anything on that but you can get into machine learning with python. Once you get the basics (arrays, functions, loops, importing libraries) then you can try out scientific libraries like numpy, matplotlib. Once, you understand what they do, you can use libraries like Scikit-Learn and Keras to get to learn more about machine learning and train your own models. There are already some guides people have prepared, check this out: https://github.com/hangtwenty/dive-into-machine-learning

**Comment by TheVip** [comment]
Thanks for the suggestion. I'll definitely look into it. Btw what projects are you doing currently...? I'm  currently trying to improve your scribd downloader. 

Also I would like to connect with you personally. Waiting eagerly for your reply.

**Comment by Ritiek** [comment]
No, not working on anything currently. Don't forget to send me a Pull Request if you do something cool with scribd!
You can always message me on Quora.
