### ISSUE TITLE
Career

### ISSUE THREAD

**Issue by Rider77** [Ritiek/ama#5]
I made a wrong decision not to give jee mains this year 2016-17 that made me feel that I ruined my career as I could have scored 200+. But now I'm thinking that maybe I should give it next year but that would be 2 years difference.Or I can learn codings in which I'm interested and take part in various coding competitions   and get a career there.
Can't I get a good job without being at NIT's or IIT's? 
So if you could help me take decision that would be very helpful.

Thank You

**Comment by Ritiek** [comment]
Why does one need to study subjects like Physics, Chemistry and you can always learn Mathematics when you would need it but if you think you can make it to some top college then it won't hurt to try. In my case, I seriously cannot drag myself for another year.. As for getting a good job, I'm not sure either but You can always look up to Anudeep Nekkanti.
